#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['typer']

package_data = \
{'': ['*']}

install_requires = \
['click >= 8.2.1', 'shellingham >= 1.3.0', 'rich >= 13.8.0', 'annotated-doc >= 0.0.2']

setup(name='typer',
      version='0.25.0',
      description='Typer, build great CLIs. Easy to code. Based on Python type hints.',
      author='Sebastián Ramírez',
      author_email='tiangolo@gmail.com',
      url='https://github.com/tiangolo/typer',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.10',
     )
